services:
  # A Django web service
  - type: web
    name: codex
    env: python
    buildCommand: chmod +x ./init_db.sh && ./build.sh
    startCommand: bash ./init_db.sh && cd CodeX && gunicorn CodeX.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: codex_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET

databases:
  - name: codex_db
    databaseName: codex
    plan: free
