# Generated by Django 4.2.7 on 2025-03-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Whether this code snippet is publicly shared'),
        ),
    ]
