# Generated by Django 4.2.7 on 2025-03-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_codesnippet_is_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='is_shared',
        ),
    ]
