# Generated by Django 5.1.7 on 2025-05-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_codesnippet_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('c', 'C'), ('java', 'Java'), ('php', 'PHP'), ('ruby', 'Ruby'), ('perl', 'Perl'), ('csharp', 'C#'), ('ocaml', 'OCaml'), ('vbnet', 'VB.NET'), ('swift', 'Swift'), ('fortran', 'Fortran'), ('haskell', 'Haskell'), ('assembly', 'Assembly'), ('prolog', 'Prolog')], max_length=20),
        ),
    ]
