# Generated by Django 5.1.7 on 2025-05-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_codesnippet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='parent_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='core.codesnippet'),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
